
cmd default() {
    echo $doc
}

/// Subcommand with a lot of nested subcommands and includes
sub sub {
    in ../dummy.run

    cmd default() {
        echo "Hello from a subcommand!"
    }

    /// This is a subcommand inside a subcommand
    sub subsub {
        in ../dummy.run
        
        cmd default() {
            echo "Hello from a subsubcommand!"
        }

        /// This is a subcommand inside a subcommand inside a subcommand
        sub subsubsub {
            in ../dummy.run

            cmd default() {
                echo "Hello from a subsubsubcommand!"
            }

            /// This is a subcommand inside a subcommand inside a subcommand inside a subcommand
            sub subsubsubsub {
                in ../dummy.run

                cmd default() {
                    echo "Hello from a subsubsubsubcommand!"
                }

                /// This is a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand
                sub subsubsubsubsub {
                    in ../dummy.run

                    cmd default() {
                        echo "Hello from a subsubsubsubsubcommand!"
                    }

                    /// This is a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand
                    sub subsubsubsubsubsub {
                        in ../dummy.run

                        cmd default() {
                            echo "Hello from a subsubsubsubsubsubcommand!"
                        }

                        /// This is a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand
                        sub subsubsubsubsubsubsub {
                            in ../dummy.run

                            cmd default() {
                                echo "Hello from a subsubsubsubsubsubsubcommand!"
                            }

                            /// This is a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand
                            sub subsubsubsubsubsubsubsub {
                                in ../dummy.run

                                cmd default() {
                                    echo "Hello from a subsubsubsubsubsubsubsubcommand!"
                                }

                                /// This is a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand
                                sub subsubsubsubsubsubsubsubsub {
                                    in ../dummy.run

                                    cmd default() {
                                        echo "Hello from a subsubsubsubsubsubsubsubsubcommand!"
                                    }

                                    /// This is a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand
                                    sub subsubsubsubsubsubsubsubsubsub {
                                        in ../dummy.run

                                        cmd default() {
                                            echo "Hello from a subsubsubsubsubsubsubsubsubsubcommand!"
                                        }

                                        /// This is a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand
                                        sub subsubsubsubsubsubsubsubsubsubsub {
                                            in ../dummy.run

                                            cmd default() {
                                                echo "Hello from a subsubsubsubsubsubsubsubsubsubsubcommand!"
                                            }

                                            /// This is a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand
                                            sub subsubsubsubsubsubsubsubsubsubsubsub {
                                                in ../dummy.run

                                                cmd default() {
                                                    echo "Hello from a subsubsubsubsubsubsubsubsubsubsubsubcommand!"
                                                }

                                                /// This is a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand
                                                sub subsubsubsubsubsubsubsubsubsubsubsubsub {
                                                    in ../dummy.run

                                                    cmd default() {
                                                        echo "Hello from a subsubsubsubsubsubsubsubsubsubsubsubsubcommand!"
                                                    }

                                                    /// This is a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand inside a subcommand
                                                    sub subsubsubsubsubsubsubsubsubsubsubsubsubsub {
                                                        in ../dummy.run

                                                        cmd default() {
                                                            echo "Hello from a subsubsubsubsubsubsubsubsubsubsubsubsubsubcommand!"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}