[package]
name = "runfile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "run"
path = "src/main.rs"

[dependencies]
ariadne = "0.4.0"
chumsky = { version = "1.0.0-alpha.6", features = ["label"] }
colored = "2.1.0"
momo = "0.2.2"
